name: identity_risk_dbt
version: "1.0.0"
config-version: 2

profile: identity_risk_dbt

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  identity_risk_dbt:
    +materialized: table