-- Purpose: create CSV file format and internal stage

USE WAREHOUSE COMPUTE_WH;
USE DATABASE IDENTITY_RISK_DB;
USE SCHEMA RAW_LAKEHOUSE;

CREATE OR REPLACE FILE FORMAT RBA_CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE RBA_INTERNAL_STAGE
  FILE_FORMAT = RBA_CSV_FORMAT;
