USE DATABASE IDENTITY_RISK_DB;
USE SCHEMA RAW_LAKEHOUSE;

COPY INTO LOGIN_EVENTS_RAW
FROM (
  SELECT
    $1  AS RTT_MS,
    $2  AS LOGIN_TIMESTAMP,
    $3  AS USER_ID,
    $4  AS UNUSED_COL,
    $5  AS IP_ADDRESS,
    $6  AS COUNTRY,
    $7  AS REGION,
    $8  AS CITY,
    $9  AS ASN,
    $10 AS USER_AGENT_STRING,
    $11 AS BROWSER_NAME_VERSION,
    $12 AS OS_NAME_VERSION,
    $13 AS DEVICE_TYPE,
    $14 AS LOGIN_SUCCESSFUL,
    $15 AS IS_ATTACK_IP,
    $16 AS IS_ACCOUNT_TAKEOVER
  FROM @RBA_INTERNAL_STAGE/rba_sample_500k.csv
)
FILE_FORMAT = (FORMAT_NAME = RBA_CSV_FORMAT)
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';
