USE DATABASE IDENTITY_RISK_DB;
USE SCHEMA RAW_LAKEHOUSE;

CREATE OR REPLACE TABLE LOGIN_EVENTS_SILVER AS
SELECT
  TRY_TO_TIMESTAMP_NTZ(LOGIN_TIMESTAMP)    AS EVENT_TS,
  USER_ID                                  AS USER_ID,
  IP_ADDRESS                               AS IP_ADDRESS,
  COUNTRY                                  AS COUNTRY,
  REGION                                   AS REGION,
  CITY                                     AS CITY,
  ASN                                      AS ASN,
  USER_AGENT_STRING                        AS USER_AGENT_STRING,
  BROWSER_NAME_VERSION                     AS BROWSER_NAME_VERSION,
  OS_NAME_VERSION                          AS OS_NAME_VERSION,
  DEVICE_TYPE                              AS DEVICE_TYPE,
  TRY_TO_NUMBER(RTT_MS)                    AS RTT_MS,
  TRY_TO_BOOLEAN(LOGIN_SUCCESSFUL)         AS LOGIN_SUCCESSFUL,
  TRY_TO_BOOLEAN(IS_ATTACK_IP)             AS IS_ATTACK_IP,
  TRY_TO_BOOLEAN(IS_ACCOUNT_TAKEOVER)      AS IS_ACCOUNT_TAKEOVER
FROM LOGIN_EVENTS_RAW
WHERE USER_ID IS NOT NULL
  AND IP_ADDRESS IS NOT NULL
  AND TRY_TO_TIMESTAMP_NTZ(LOGIN_TIMESTAMP) IS NOT NULL;
