USE DATABASE IDENTITY_RISK_DB;
USE SCHEMA RAW_LAKEHOUSE;

CREATE OR REPLACE TABLE GOLD_LOGIN_KPIS_5M AS
WITH base AS (
  SELECT
    EVENT_TS,
    DATEADD(
      MINUTE,
      - MOD(DATE_PART('MINUTE', EVENT_TS), 5),
      DATE_TRUNC('MINUTE', EVENT_TS)
    ) AS WINDOW_START_5M,
    LOGIN_SUCCESSFUL,
    RTT_MS,
    IS_ATTACK_IP,
    IS_ACCOUNT_TAKEOVER
  FROM LOGIN_EVENTS_SILVER
)
SELECT
  WINDOW_START_5M,
  DATEADD(MINUTE, 5, WINDOW_START_5M) AS WINDOW_END_5M,
  COUNT(*) AS LOGIN_ATTEMPTS,
  SUM(IFF(LOGIN_SUCCESSFUL = FALSE, 1, 0)) AS FAILED_LOGINS,
  SUM(IFF(LOGIN_SUCCESSFUL = TRUE,  1, 0)) AS SUCCESSFUL_LOGINS,
  (SUCCESSFUL_LOGINS / NULLIF(LOGIN_ATTEMPTS, 0)) AS SUCCESS_RATE,
  AVG(RTT_MS) AS AVG_RTT_MS,
  SUM(IFF(IS_ATTACK_IP = TRUE, 1, 0)) AS ATTACK_IP_EVENTS,
  SUM(IFF(IS_ACCOUNT_TAKEOVER = TRUE, 1, 0)) AS ACCOUNT_TAKEOVER_EVENTS
FROM base
GROUP BY WINDOW_START_5M
ORDER BY WINDOW_START_5M;
