USE DATABASE IDENTITY_RISK_DB;
USE SCHEMA RAW_LAKEHOUSE;

CREATE OR REPLACE TABLE GOLD_RISK_SIGNALS_BY_USER AS
SELECT
  USER_ID,
  COUNT(*) AS LOGIN_ATTEMPTS,
  SUM(IFF(LOGIN_SUCCESSFUL = FALSE, 1, 0)) AS FAILED_LOGINS,
  SUM(IFF(LOGIN_SUCCESSFUL = TRUE,  1, 0)) AS SUCCESSFUL_LOGINS,
  (FAILED_LOGINS / NULLIF(LOGIN_ATTEMPTS, 0)) AS FAILURE_RATE,
  SUM(IFF(IS_ATTACK_IP = TRUE, 1, 0)) AS ATTACK_IP_EVENTS,
  SUM(IFF(IS_ACCOUNT_TAKEOVER = TRUE, 1, 0)) AS ACCOUNT_TAKEOVER_EVENTS,
  AVG(RTT_MS) AS AVG_RTT_MS,
  MIN(EVENT_TS) AS FIRST_SEEN_TS,
  MAX(EVENT_TS) AS LAST_SEEN_TS,
  (FAILED_LOGINS * 1.0) +
  (ATTACK_IP_EVENTS * 3.0) +
  (ACCOUNT_TAKEOVER_EVENTS * 5.0) AS RISK_SCORE
FROM LOGIN_EVENTS_SILVER
GROUP BY USER_ID
ORDER BY RISK_SCORE DESC, FAILED_LOGINS DESC;